Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25
    
