language: ruby

script: bundle exec rake test
rvm:
  - 2.2.1
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7


notifications:
  slack:
    secure: GVD9d+kwR5hzab5ZnWugbCkp9QSYyheSrABWkD+LmpMcWcx7jijajSn4LLvDi/zHYn1MdOBcPe08hSygmpm7ViUApp0EJcSzE4BLU/5oAs+ANV0Qq6jsssMlyo3v8eRAqHNiLxAiAsz+lc0EZWfQnSW8kHzzbO3NeYq1NRL5CgQ=
